version: 2
jobs:
  build:
    working_directory: ~/oysteR
    docker:
      - image: rocker/verse:3.6.1
    steps:
      - checkout
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz --as-cran
      - run:
          name: Move R built package
          command: mkdir built && mv oysteR_*.tar.gz built
      - store_artifacts:
          path: ~/oysteR/oysteR.Rcheck/
      - store_artifacts:
          path: ~/oysteR/built/

